### ISSUE TITLE
KD_JPEG会开源吗？

### ISSUE THREAD

**Issue by qq843626244** [yingqichao/imuge_plus#4]
您好，KD_JPEG的代码我在您回答issue的链接中找到了，但是我想请问一下KD_JPEG的权值会公开吗？

**Comment by yingqichao** [comment]
> 您好，KD_JPEG的代码我在您回答issue的链接中找到了，但是我想请问一下KD_JPEG的权值会公开吗？

好的没问题，不过稍等哦，因为我现在毕业了，学校账号什么的全都过期不能用了，得下次我进学校里面连内网了才能把实验室服务器里面存的ckpt传到google drive上。

**Comment by yingqichao** [comment]
你好, checkpoint的link放在readme里了
